# The URL the site will be built for
base_url = "https://jjj-ade.github.io/"
title = "JJJade Log"
theme = "goyo"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
default_language = "ko"
generate_feeds = true
generate_sitemap = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
bottome_footnotes = true
highlight_theme = "ayu-mirage"

[extra]
# Put all your custom variables here
default_colorset = "light"
logo_text = "JADE LOG"
logo_image_path = "images/tomato.png"
disable_theme_toggle = true

nav = [
  { name = "Categories", type = "dropdown", icon = "fa-solid fa-star", members = [
      { name = "WIL", url = "/study/wil", icon = "fa-solid fa-book" }
  ] },
  { name = "Link", type = "dropdown", icon = "fa-solid fa-paperclip", members = [
    { name = "Github", url = "https://github.com/JJJ-ade\" target=\"_blank\" rel=\"noopener noreferrer", type = "url", icon = "fa-brands fa-github" }
  ] }
]

default_thumbnail = "images/tomato.png"

[extra.comments]
enabled = true
system = "giscus"
repo = "JJJ-ade/JJJ-ade.github.io"
repo_id = "R_kgDOQlRS7g"
category = "Announcements"
category_id = "DIC_kwDOQlRS7s4CzqPs"
mapping = "pathname"
strict = "0"
reactions_enabled = "1"
emit_metadata = "0"
input_position = "bottom"
theme = "noborder_light"
lang = "ko"