base_url = "https://JJJ-ade.github.io/JJJadelog/"
title = "JJJade"
theme = "goyo"

compile_sass = false
build_search_index = false

[markdown]
highlight_code = false

[extra]
# Logo Configuration (적당히 바꿔도 됨)
logo_text = "JJJade Log"
logo_image_path = "images/goyo.png"
logo_image_padding = "5px"

# Footer Configuration
footer_html = "Powered by <a href='https://www.getzola.org'>Zola</a> and <a href='https://github.com/hahwul/goyo'>Goyo</a>"

# Navigation Configuration (상단 메뉴)
nav = [
  { name = "Docs", url = "/introduction", type = "url", icon = "fa-solid fa-book" },
  { name = "GitHub", url = "https://github.com/JJJ-ade/JJJadelog", type = "url", icon = "fa-brands fa-github" },
]

landing = [
    { title = "Hello World", link = "hello-world", desc = "첫 포스트입니다." },
]
